# Generated by Django 6.0.2 on 2026-02-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CricketPlayerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=150)),
                ('JerseyNo', models.IntegerField()),
                ('country', models.CharField(max_length=150)),
                ('playerType', models.CharField(max_length=150)),
            ],
        ),
    ]
