# Generated by Django 6.0.2 on 2026-03-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=150)),
                ('Age', models.IntegerField()),
                ('disease', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
            ],
        ),
    ]
